"""Contratos de persistência usados pela camada de aplicação.

Os contratos são estruturais: ``Database`` já os atende sem precisar herdar
deles. Isso permite trocar SQLite por outra implementação gradualmente.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from src.domain.combat import Skill


@runtime_checkable
class CharacterRepository(Protocol):
    def create_character(self, guild_id: int, user_id: int, name: str) -> None: ...
    def get_character(self, guild_id: int, user_id: int) -> Any: ...
    def list_characters(self, guild_id: int) -> list[Any]: ...
    def change_sp(self, guild_id: int, user_id: int, delta: int) -> Any: ...
    def set_levels(self, guild_id: int, user_id: int, offense: int, defense: int) -> Any: ...


@runtime_checkable
class SkillRepository(Protocol):
    def save_skill(self, guild_id: int, owner_id: int, skill: Skill) -> None: ...
    def get_skill(self, guild_id: int, owner_id: int, name: str) -> Skill | None: ...
    def list_skills(self, guild_id: int, owner_id: int) -> list[Skill]: ...
    def delete_skill(self, guild_id: int, owner_id: int, name: str) -> bool: ...


@runtime_checkable
class EnemyRepository(Protocol):
    def get_enemy(self, guild_id: int, name: str) -> Any: ...
    def list_enemies(self, guild_id: int) -> list[Any]: ...
    def get_enemy_skill(self, enemy_id: int, name: str) -> Skill | None: ...
    def list_enemy_skills(self, enemy_id: int) -> list[Skill]: ...

