import { useEffect, useState } from 'react'
import { RotateCcw, Save } from 'lucide-react'
import { Modal } from '../ui/Modal'
import { Button } from '../ui/Button'
import { NumberField, TextField, TextAreaField } from '../ui/Input'
import { computedProficiencies, levelValues } from '../../progression'

const keyOf = name => ({ Força:'strength', Destreza:'dexterity', Constituição:'constitution', Inteligência:'intelligence', Sabedoria:'wisdom', Carisma:'charisma' }[name] || String(name).toLowerCase())
const sections = { overview:['Dados técnicos','Controle local: recursos, nível, atributos e resistências.'], identity:['Identidade','Dados narrativos vinculados à ficha.'], attributes:['Progressão e perícias','Marque somente o que é treinado; o bônus é calculado pelo nível.'] }
const defaultResistances = [{name:'Corte',value:'1.0×'},{name:'Perfuração',value:'1.0×'},{name:'Contusão',value:'1.0×'}]

export function SheetEditModal({ character, section='overview', open, onClose, onSave }) {
  const fresh = () => ({ ...character, profile:character.profile || {}, uptie:character.uptie || 1, identity:character.identity || {}, resistances:character.resistances?.length ? character.resistances : defaultResistances })
  const [draft, setDraft] = useState(fresh), [saving,setSaving] = useState(false), [error,setError] = useState('')
  useEffect(() => { if (open) { setDraft(fresh()); setError('') } }, [open, character])
  if (!open) return null
  const set = (key,value) => setDraft(current => ({...current,[key]:value}))
  const setIdentity = (key,value) => setDraft(current => ({...current,identity:{...current.identity,[key]:value}}))
  const meter = (key,value) => setDraft(current => ({...current,[key]:{...current[key],current:Math.max(0,Number(value))}}))
  const attribute = (name,value) => setDraft(current => ({...current,attributes:current.attributes.map(item => item.name === name ? {...item,value:Number(value)} : item)}))
  const resistance = (index,value) => setDraft(current => ({...current,resistances:current.resistances.map((item,i) => i === index ? {...item,value} : item)}))
  const toggle = name => setDraft(current => ({...current,proficiencies:current.proficiencies?.some(item => (typeof item === 'string' ? item : item.name) === name) ? current.proficiencies.filter(item => (typeof item === 'string' ? item : item.name) !== name) : [...(current.proficiencies || []),name]}))
  const attrs = Object.fromEntries((draft.attributes || []).map(item => [keyOf(item.name),Number(item.value)]))
  const scaling = levelValues({level:draft.level,strength:attrs.strength,constitution:attrs.constitution,hpRollTotal:draft.profile?.hp_roll_total || 54})
  const proficiencies = computedProficiencies(attrs,draft.proficiencies,draft.level)
  const save = async () => { setSaving(true); setError(''); try { await onSave?.({...draft.profile,_update_combat_sp:true,special_effect_name:String(draft.profile?.special_effect_name || '').trim() || 'Efeito Trashholder',uptie:draft.uptie,level:Number(draft.level || 1),hp_roll_total:Number(draft.profile?.hp_roll_total || 54),max_hp_override:Math.max(0,Number(draft.profile?.max_hp_override || 0)),hp:draft.hp.current,sp:draft.sp.current,light:draft.light.current,stagger:draft.stagger.current,rd:Number(draft.rd || 0),movement:Number(draft.movement || 0),attributes:attrs,identity:draft.identity,proficiencies:draft.proficiencies,resistances:draft.resistances,records:draft.profile?.records || {}}) } catch (cause) { setError(cause.message || 'Não foi possível salvar.') } finally { setSaving(false) } }
  const [title,tip] = sections[section] || sections.overview
  const statRows = [['Nível','level'],['HP atual','hp'],['Light atual','light'],['RD','rd'],['Stagger atual','stagger'],['Sanidade','sp'],['Deslocamento','movement']]
  return <Modal title={title} eyebrow="EDIÇÃO LOCAL" open={open} onClose={onClose} footer={<><Button variant="ghost" icon={RotateCcw} onClick={() => setDraft(fresh())}>Desfazer</Button><Button variant="solid" icon={Save} disabled={saving} onClick={save}>{saving ? 'Salvando…' : 'Salvar'}</Button></>}>
    <p className="identification-lock">{tip}</p>
    {section === 'overview' && <section className="special-effect-name"><span>EFEITO TRASHHOLDER DA FICHA</span><input maxLength="40" placeholder="Ex.: Falsa Fome" value={draft.profile?.special_effect_name || 'Efeito Trashholder'} onChange={e => setDraft(current => ({...current,profile:{...current.profile,special_effect_name:e.target.value}}))}/><small>Usa o emoji PlH e muda somente o nome exibido nesta ficha.</small></section>}
    {section === 'overview' && <>
      <section className="uptie-select"><span>UPTIE ATUAL</span><select value={draft.uptie} onChange={e => set('uptie',Number(e.target.value))}>{[1,2,3,4,5].map(item => <option value={item} key={item}>{['I','II','III','IV','V'][item-1]}</option>)}</select></section>
      <section className="maximum-hp-editor"><div><span>VIDA MÁXIMA</span><small>O cálculo automático continua ativo. Use 0 para voltar a ele.</small></div><input type="number" min="0" value={draft.profile?.max_hp_override || ''} placeholder={String(scaling.maxHp)} onChange={e => setDraft(current => ({...current,profile:{...current.profile,max_hp_override:Math.max(0,Number(e.target.value || 0))}}))}/><strong>Automático {scaling.maxHp} · Em uso {Number(draft.profile?.max_hp_override || 0) || scaling.maxHp}</strong></section>
      <div className="rosemary-editor-grid"><section className="technical-column"><h3>Estatísticas</h3>{statRows.map(([label,key]) => <div className="technical-number" key={key}><span>{label}</span>{['hp','light','stagger','sp'].includes(key) ? <input type="number" value={draft[key]?.current ?? 0} onChange={e => meter(key,e.target.value)}/> : <input type="number" value={draft[key] ?? 0} min="1" onChange={e => set(key,Number(e.target.value))}/>}</div>)}<div className="derived-values"><span>Offense <b>{scaling.offense}</b></span><span>Defense <b>{scaling.defense}</b></span><span>HP automático <b>{scaling.maxHp}</b></span><span>Stagger máx. <b>{Math.floor((Number(draft.profile?.max_hp_override || 0) || scaling.maxHp)/2)}</b></span><span>Light máximo <b>{scaling.maxLight}</b></span></div></section><section className="technical-column"><h3>Atributos</h3>{draft.attributes.map(item => <div className="technical-number" key={item.name}><span>{item.name} <i>{Math.floor((Number(item.value)-10)/2) >= 0 ? '+' : ''}{Math.floor((Number(item.value)-10)/2)}</i></span><input type="number" value={item.value} onChange={e => attribute(item.name,e.target.value)}/></div>)}</section><section className="technical-column"><h3>Resistências</h3>{draft.resistances.map((item,index) => <div className="technical-number" key={item.name}><span>{item.name}</span><select value={item.value || item.tier || '1.0×'} onChange={e => resistance(index,e.target.value)}><option>2.0×</option><option>1.5×</option><option>1.0×</option><option>0.5×</option><option>0.0×</option></select></div>)}</section></div>
    </>}
    {section === 'identity' && <section className="edit-section"><div className="edit-grid"><TextField label="Nome" value={draft.identity.name || draft.name || ''} onChange={e => setIdentity('name',e.target.value)}/><TextField label="Idade" value={draft.identity.age || ''} onChange={e => setIdentity('age',e.target.value)}/><TextField label="Altura e peso" value={draft.identity.height_weight || ''} onChange={e => setIdentity('height_weight',e.target.value)}/><TextField label="Gênero" value={draft.identity.gender || ''} onChange={e => setIdentity('gender',e.target.value)}/><TextField label="Sexualidade" value={draft.identity.sexuality || ''} onChange={e => setIdentity('sexuality',e.target.value)}/><TextField label="Association / Syndicate" value={draft.identity.affiliation || ''} onChange={e => setIdentity('affiliation',e.target.value)}/><TextField label="E.G.O." value={draft.identity.ego || ''} onChange={e => setIdentity('ego',e.target.value)}/></div><TextAreaField label="Descrição" value={draft.identity.description || ''} onChange={e => setIdentity('description',e.target.value)}/><TextAreaField label="Aparência" value={draft.identity.appearance || ''} onChange={e => setIdentity('appearance',e.target.value)}/></section>}
    {section === 'attributes' && <section className="edit-section"><div className="edit-section-heading"><div><span>PERÍCIAS</span><h3>Treinamento</h3></div><small>◆ treinada (+{scaling.trainedGrade}) · ◇ não treinada (+{scaling.untrainedGrade})</small></div><div className="proficiency-editor">{proficiencies.map(item => <button type="button" className={item.trained ? 'selected' : ''} onClick={() => toggle(item.name)} key={item.name}><i>{item.trained ? '◆' : '◇'}</i><span>{item.name}{item.requirement ? `-${item.requirement}` : ''}</span><small>{item.attribute.slice(0,3).toUpperCase()}</small><b>{item.value >= 0 ? '+' : ''}{item.value}</b></button>)}</div></section>}
    {error && <p className="edit-error">{error}</p>}
  </Modal>
}
