import { useState } from 'react'
import { EntityCard } from '../ui/EntityCard'
import { useActivityData } from '../../activityData'

const blank=()=>({name:'',old_name:'',skill_slot:'s1',skill_type:'attack',base_power:4,coin_power:2,coins:1,description:'',coin_layout:['normal'],effects:[]})
const triggers=['on_use','before_attack','on_hit','heads_hit','on_crit','clash_win','clash_lose','after_attack','on_kill']
const types=['bleed','burn','tremor','rupture','sinking','poise','charge','paralysis','haste','offense_level','defense_level','clash_power','base_power','coin_power','final_power','damage_percent','sp','special_condition','tremor_burst','amplitude_conversion_scorch','reuse_coin','make_unbreakable','consume_special_condition','self_bleed','bloodfeast','consume_bloodfeast','unique_bloodfeast','unique_bleed','glimpse_of_precognition']
const skillTypes=[['attack','Ataque'],['guard','Guarda'],['evade','Evasiva'],['counter','Counter'],['clashable_guard','Guarda Clashable'],['clashable_counter','Counter Clashable'],['assist_defense','Defesa Assistida']]
const skillSlots=[...['s1','s2','s3'].flatMap(base=>[[base,base.toUpperCase()],...Array.from({length:10},(_,i)=>[`${base}-${i+1}`,`${base.toUpperCase()}-${i+1}`])]),...Array.from({length:5},(_,i)=>{const base=`d${i+1}`;return [[base,`Defensiva ${i+1}`],...Array.from({length:5},(_,v)=>[`${base}-${v+1}`,`Defensiva ${i+1}-${v+1}`])] }).flat()]
const conditionTypes=['','burn','bleed','tremor','rupture','sinking','poise','charge','haste','paralysis','sp','base_power','coin_power','clash_power','offense_level','defense_level','special_condition','special_condition_consumed','bloodfeast','bloodfeast_consumed','shared_bloodfeast_consumed','bloodfiend_or_bloodbag']
const nice=x=>String(x||'').replaceAll('_',' ')
const effectLabel=(x,specialName='Efeito Trashholder')=>({
  on_use:'Ao Usar (On Use)',before_attack:'Antes do Ataque',on_hit:'Ao Acertar (On Hit)',heads_hit:'Ao Acertar Cara (Heads)',on_crit:'Ao Causar Crítico',clash_win:'Ao Vencer Clash',clash_lose:'Ao Perder Clash',after_attack:'Após o Ataque',on_kill:'Ao Derrotar Alvo',on_evade:'Ao Esquivar',
  damage_percent:'Bônus de dano (%)',final_power:'Final Power',base_power:'Base Power',coin_power:'Coin Power',clash_power:'Clash Power',offense_level:'Offense Level',defense_level:'Defense Level',special_condition:specialName,consume_special_condition:`Consumir ${specialName}`,special_condition_consumed:`${specialName} consumido`,tremor_burst:'Tremor Burst',amplitude_conversion_scorch:'Amplitude Conversion → Tremor - Scorch',reuse_coin:'Reutilizar moeda',make_unbreakable:'Tornar moeda inquebrável',bloodfeast:'Bloodfeast',bloodfeast_consumed:'Bloodfeast Consumido',shared_bloodfeast_consumed:'Bloodfeast Consumido (Compartilhado)',unique_bloodfeast:'Bloodfeast Único',unique_bleed:'Bleed Único',consume_bloodfeast:'Consumir Bloodfeast',glimpse_of_precognition:'Glimpse of Precognition',bloodfiend_or_bloodbag:'Bloodfiend ou Bloodbag'
}[x]||nice(x))
const skillTriggers=skillType=>skillType==='evade'?[...triggers,'on_evade']:triggers
const effectAsset=(assets,type)=>{const aliases={tremor_burst:'tremor',amplitude_conversion_scorch:'tremor',self_bleed:'bleed',consume_special_condition:'special_condition',special_condition_consumed:'special_condition',reuse_coin:'coin_active',make_unbreakable:'coin_unbreakable',bloodfeast_consumed:'bloodfeast',shared_bloodfeast_consumed:'bloodfeast',consume_bloodfeast:'bloodfeast',unique_bloodfeast:'bloodfeast',unique_bleed:'bleed',bloodfiend_or_bloodbag:'bloodfiend'};return assets[type]?.url||assets[aliases[type]]?.url||''}
const effectSummary=(item,specialName)=>{if(!item.trigger||!item.effect_type)return 'Selecione primeiro o gatilho e o efeito.';if(item.effect_type==='reuse_coin')return `Ao causar crítico, reutiliza ${item.coin?`a moeda ${item.coin}`:'a moeda que critou'} até ${Math.max(1,Math.min(5,Number(item.value)||1))} vez(es).`;const owner=({all_allies:'em todos os aliados do encontro',faction:'só nos aliados da facção do gift'}[item.effect_owner])||(item.effect_owner==='user'?'em si mesmo':item.effect_owner==='target'?'no alvo':'no destino automático');const value=`${effectLabel(item.effect_type,specialName)} ${Number(item.value)>=0?'+':''}${item.value}${item.effect_type==='damage_percent'?'%':''}`;if(!item.condition_status)return `${value} ${owner}, sem condição.`;const where=item.condition_owner==='user'?'em si mesmo':'no alvo';const metric=item.condition_value==='count'?'Count':'Potência';const rule={has:'possuir',at_least:'ter pelo menos',at_most:'ter no máximo',exactly:'ter exatamente'}[item.condition_operator||'at_least'];const reference=(item.condition_operator||'at_least')==='has'?'':` ${item.condition_min||0} de ${metric}`;const scale=item.condition_per?` O bônus aumenta novamente a cada ${item.condition_per}, até ${item.condition_max_stacks||'sem limite'} vez(es).`:'';return `${value} ${owner} quando ${where} ${rule} ${effectLabel(item.condition_status,specialName)}${reference}.${scale}`}

function ConditionPicker({value,onChange,assets,specialName}){return <div className="condition-field"><span>CONDIÇÃO</span><div className="condition-picker">{conditionTypes.map(type=>{const icon=effectAsset(assets,type);return <button type="button" className={(value||'')===type?'selected':''} onClick={()=>onChange(type)} key={type||'none'}>{icon?<img src={icon} alt=""/>:<i>{type==='sp'?'SP':type==='defense_level'?'◆':'◇'}</i>}<small>{type?effectLabel(type,specialName):'Sem condição'}</small></button>})}</div></div>}

export function SkillsTab({skills=[],onSave,onDelete}) {
  const {uiAssets={},character}=useActivityData()
  const specialEffectName=character?.specialEffectName||'Efeito Trashholder'
  const [draft,setDraft]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState('')
  const set=(key,value)=>setDraft(current=>({...current,[key]:value}))
  const setSkillType=value=>setDraft(current=>({...current,skill_type:value,effects:current.effects.map(item=>item.trigger==='on_evade'&&value!=='evade'?{...item,trigger:''}:item)}))
  const edit=skill=>setDraft({name:skill.name,old_name:skill.name,skill_slot:skill.skillSlot||'s1',skill_type:skill.skillType||'attack',base_power:skill.basePower,coin_power:skill.coinPower,coins:skill.coins,description:skill.description||'',coin_layout:Array.from({length:skill.coins},(_,i)=>skill.coinTypes.unbreakable&&i>=skill.coins-skill.coinTypes.unbreakable?'unbreakable':'normal'),effects:skill.effects.map(({emoji,...effect})=>effect)})
  const setCoins=value=>{const coins=Math.max(1,Math.min(10,Number(value)));setDraft(current=>({...current,coins,coin_layout:Array.from({length:coins},(_,i)=>current.coin_layout[i]||'normal')}))}
  const effect=(index,key,value)=>setDraft(current=>({...current,effects:current.effects.map((item,i)=>{if(i!==index)return item;const next={...item,[key]:value,...(key==='effect_type'&&value==='charge'?{effect_owner:'user'}:{})};if(key==='condition_status'&&!value)return {...next,condition_status:'',condition_owner:'',condition_value:'',condition_operator:'',condition_min:'',condition_per:'',condition_max_stacks:'',consume_condition:false};return next})}))
  const save=async event=>{event.preventDefault();setSaving(true);setError('');try{await onSave?.({...draft,coins:Number(draft.coins),base_power:Number(draft.base_power),coin_power:Number(draft.coin_power),coin_layout:draft.coin_layout.slice(0,Number(draft.coins))});setDraft(blank())}catch(cause){setError(cause.message||'Não foi possível salvar a skill.')}finally{setSaving(false)}}
  return <div className="skills-workshop">
    <div className="cards-grid">{skills.map(skill=><EntityCard key={skill.id} type="skill" eyebrow={`${skill.slot} · ${skill.damageType}`} title={skill.name}>
      <button className="skill-card-action" onClick={()=>edit(skill)}>Editar</button>
      <div className="skill-power-row"><div><span>BASE POWER</span><strong>{skill.basePower}</strong></div><div><span>COIN POWER</span><strong>{skill.coinPower}</strong></div></div>
      <div className="coin-row">{Array.from({length:skill.coins},(_,index)=>{const unbreakable=skill.coinTypes.unbreakable&&index>=skill.coins-skill.coinTypes.unbreakable;const asset=unbreakable?uiAssets.coin_unbreakable:uiAssets.coin_active;return <span className={`coin ${unbreakable?'coin-unbreakable':skill.coinPower>=0?'coin-positive':'coin-negative'}`} key={index} title={`Moeda ${index+1}: ${unbreakable?'Inquebrável':skill.coinPower>=0?'Plus Coin':'Minus Coin'}`}>{asset?.url?<img src={asset.url} alt={unbreakable?'Moeda inquebrável':skill.coinPower>=0?'Plus Coin':'Minus Coin'}/>:unbreakable?'◆':skill.coinPower>=0?'+':'−'}</span>})}<small>{skill.coins} moeda(s)</small></div>
      <p>{skill.description}</p>{skill.effects.length>0&&<ul className="effects-list">{skill.effects.map((item,index)=><li className="skill-effect" key={index}>{item.emoji&&<img src={item.emoji} alt=""/>}<b>[{nice(item.trigger).toUpperCase()}]</b> {effectLabel(item.effect_type,specialEffectName)} {Number(item.value)>=0?'+':''}{item.value}{item.count?` · Count +${item.count}`:''}</li>)}</ul>}
    </EntityCard>)}</div>
    <form className="skill-workshop-form" onSubmit={save}>
      <header><div><span>OFICINA DE SKILL</span><h3>{draft.old_name?`Editando: ${draft.old_name}`:'Nova skill'}</h3></div>{draft.old_name&&<button type="button" onClick={()=>onDelete?.(draft.old_name).then(()=>setDraft(blank()))}>Excluir</button>}</header>
      <div className="skill-form-grid">
        <label>Nome<input required maxLength="50" value={draft.name} onChange={e=>set('name',e.target.value)}/></label>
        <label>Posição<select value={draft.skill_slot} onChange={e=>set('skill_slot',e.target.value)}>{skillSlots.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
        <label>Tipo<select value={draft.skill_type} onChange={e=>setSkillType(e.target.value)}>{skillTypes.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
        <label>Base Power<input type="number" value={draft.base_power} onChange={e=>set('base_power',e.target.value)}/></label>
        <label>Coin Power<input type="number" value={draft.coin_power} onChange={e=>set('coin_power',e.target.value)}/></label>
        <label>Moedas<input type="number" min="1" max="10" value={draft.coins} onChange={e=>setCoins(e.target.value)}/></label>
        <label className="skill-description">Descrição<textarea value={draft.description} onChange={e=>set('description',e.target.value)}/></label>
      </div>
      <div className="coin-builder"><span>TIPO DE MOEDAS</span>{draft.coin_layout.map((kind,index)=>{const asset=kind==='unbreakable'?uiAssets.coin_unbreakable:uiAssets.coin_active;return <button type="button" className={kind} key={index} title={`Moeda ${index+1}: ${kind==='unbreakable'?'Inquebrável':'Normal'} — clique para trocar`} onClick={()=>setDraft(current=>({...current,coin_layout:current.coin_layout.map((item,i)=>i===index?(item==='normal'?'unbreakable':'normal'):item)}))}>{asset?.url?<img src={asset.url} alt={kind==='unbreakable'?'Moeda inquebrável':'Moeda normal'}/>:kind==='unbreakable'?'◆':draft.coin_power>=0?'+':'−'}<small>{index+1}</small></button>})}<em>Clique em uma moeda para alternar Normal ↔ Inquebrável.</em></div>
      <div className="effect-builder"><header><span>EFEITOS E GATILHOS</span><button type="button" onClick={()=>setDraft(current=>({...current,effects:[...current.effects,{trigger:'',effect_type:'',value:'',count:'',coin:'',effect_owner:'',charge_cost:'',condition_status:'',condition_owner:'',condition_value:'',condition_operator:'',condition_min:'',condition_per:'',condition_max_stacks:'',consume_condition:false}]}))}>+ Efeito</button></header>
        {draft.effects.map((item,index)=><article key={index}>
          <p className="effect-summary">{effectSummary(item,specialEffectName)}</p>
          <div className="effect-main-row"><select value={item.trigger||''} onChange={e=>effect(index,'trigger',e.target.value)}><option value="" disabled>Selecione o gatilho</option>{skillTriggers(draft.skill_type).map(x=><option value={x} key={x}>{effectLabel(x)}</option>)}</select><div className="effect-type-select">{effectAsset(uiAssets,item.effect_type)&&<img src={effectAsset(uiAssets,item.effect_type)} alt=""/>}<select value={item.effect_type||''} onChange={e=>effect(index,'effect_type',e.target.value)}><option value="" disabled>Selecione o efeito</option>{types.map(x=><option value={x} key={x}>{effectLabel(x)}</option>)}</select></div><input type="number" min={item.effect_type==='reuse_coin'?1:undefined} max={item.effect_type==='reuse_coin'?5:undefined} step={item.effect_type==='damage_percent'?'0.1':'1'} value={item.value??''} onChange={e=>effect(index,'value',e.target.value)} title={item.effect_type==='reuse_coin'?'Máximo de reutilizações (1–5)':item.effect_type==='damage_percent'?'Porcentagem de dano':'Potência ou valor'} placeholder="Valor"/><input type="number" value={item.count??''} onChange={e=>effect(index,'count',e.target.value)} placeholder="Count"/><input type="number" min="1" max={draft.coins} value={item.coin??''} onChange={e=>effect(index,'coin',e.target.value)} placeholder="Moeda"/><button type="button" onClick={()=>setDraft(current=>({...current,effects:current.effects.filter((_,i)=>i!==index)}))}>×</button></div>
          <div className="effect-options-row">
            <label>Quem recebe<select value={item.effect_owner||''} onChange={e=>effect(index,'effect_owner',e.target.value)}><option value="" disabled>Selecione</option><option value="target">No Alvo (Oponente)</option><option value="user">Em Si Mesmo (Conjurador)</option><option value="auto">Automático / Padrão</option><option value="all_allies">Em Todos os Aliados do Encontro</option><option value="faction">Só nos Aliados da Facção (keyword do gift)</option></select></label>
            <label>Charge gasta<input type="number" min="0" value={item.charge_cost??''} onChange={e=>effect(index,'charge_cost',e.target.value)} placeholder="Nenhuma"/></label>
            <ConditionPicker value={item.condition_status} onChange={value=>effect(index,'condition_status',value)} assets={uiAssets} specialName={specialEffectName}/>
            {item.condition_status&&<>
              <label>Onde verificar<select value={item.condition_owner||''} onChange={e=>effect(index,'condition_owner',e.target.value)}><option value="" disabled>Selecione</option><option value="target">No alvo</option><option value="user">Em si mesmo</option></select></label>
              <label>Regra<select value={item.condition_operator||''} onChange={e=>effect(index,'condition_operator',e.target.value)}><option value="" disabled>Selecione</option><option value="has">Apenas possuir</option><option value="at_least">Pelo menos</option><option value="at_most">No máximo</option><option value="exactly">Exatamente</option></select></label>
              <label>Medir<select value={item.condition_value||''} onChange={e=>effect(index,'condition_value',e.target.value)}><option value="" disabled>Selecione</option><option value="potency">Potência</option><option value="count">Count</option></select></label>
              {item.condition_operator!=='has'&&<label>Valor necessário<input type="number" min={['sp','base_power','coin_power','clash_power','offense_level','defense_level'].includes(item.condition_status)?-99:0} max={item.condition_status==='sp'?45:undefined} value={item.condition_min??''} onChange={e=>effect(index,'condition_min',e.target.value)}/></label>}
              <label>Novo bônus a cada<input type="number" min="0" value={item.condition_per??''} onChange={e=>effect(index,'condition_per',e.target.value)} placeholder="Não repete"/></label>
              <label>Limite de bônus<input type="number" min="0" value={item.condition_max_stacks??''} onChange={e=>effect(index,'condition_max_stacks',e.target.value)} placeholder="Sem limite"/></label>
              <label className="effect-check"><input type="checkbox" checked={Boolean(item.consume_condition)} onChange={e=>effect(index,'consume_condition',e.target.checked)}/> Gastar condição ao ativar</label>
            </>}
          </div>
        </article>)}
      </div>
      {error&&<p className="edit-error">{error}</p>}<footer><button type="button" onClick={()=>setDraft(blank())}>Limpar</button><button type="submit" disabled={saving}>{saving?'Salvando…':'Salvar na ficha'}</button></footer>
    </form>
  </div>
}
