import {useState} from 'react'
import {AlertTriangle,BrainCircuit,HeartPulse,ShieldCheck,Sparkles} from 'lucide-react'
import {CombatMeter} from '../ui/CombatMeter'
const effects=['burn','bleed','tremor','rupture','sinking','poise','charge','haste','special_condition']
export function StatusTab({character,statuses,onSave}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState([]),[saving,setSaving]=useState(false),[error,setError]=useState(''),sp=character.sp.current,state=sp<=-45?'PÂNICO':sp>=45?'SANIDADE MÁXIMA':'CONTIDA'
 const edit=()=>{setDraft(statuses.map(x=>({status_type:x.type||x.status_type||'bleed',potency:x.potency,count:x.count})));setOpen(true)}
 const save=async()=>{setSaving(true);try{await onSave(draft);setOpen(false)}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="status-dossier"><section className="status-vitals"><header><span>SINAIS VITAIS</span><strong>{state}</strong></header><CombatMeter label="INTEGRIDADE // HP" tone="hp" current={character.hp.current} maximum={character.hp.maximum}/><CombatMeter label="SANIDADE // SP" tone="sp" current={sp} maximum={45}/><CombatMeter label="LIGHT" tone="light" current={character.light.current} maximum={character.light.maximum}/></section><section className="status-rules"><article><HeartPulse/><div><h3>Vida e Stagger</h3><p>Vida máxima cresce com o nível e Constituição.</p></div></article><article><BrainCircuit/><div><h3>Sanidade</h3><p>Vai de −45 a +45.</p></div></article><article><Sparkles/><div><h3>Light</h3><p>Recurso da ficha.</p></div></article></section><section className="status-effects"><header><span>EFEITOS ATIVOS</span><small>{statuses.length} REGISTRADOS</small>{onSave&&<button onClick={edit}>Editar efeitos</button>}</header>{statuses.length?<div className="status-effect-list">{statuses.map(x=><article key={x.id||x.name}><div className="effect-icon">{x.emoji?<img src={x.emoji} alt=""/>:<AlertTriangle/>}</div><div><strong>{x.name}</strong><p>{x.description}</p></div><b>{x.potency} P / {x.count} C</b></article>)}</div>:<p className="empty-note">Nenhum efeito ativo no momento.</p>}{open&&<div className="player-effects-editor">{draft.map((x,i)=><p key={i}><select value={x.status_type} onChange={e=>setDraft(a=>a.map((v,n)=>n===i?{...v,status_type:e.target.value}:v))}>{effects.map(t=><option value={t} key={t}>{t.replaceAll('_',' ')}</option>)}</select><input type="number" min="0" value={x.potency} onChange={e=>setDraft(a=>a.map((v,n)=>n===i?{...v,potency:Number(e.target.value)}:v))}/><input type="number" min="0" value={x.count} onChange={e=>setDraft(a=>a.map((v,n)=>n===i?{...v,count:Number(e.target.value)}:v))}/><button onClick={()=>setDraft(a=>a.filter((_,n)=>n!==i))}>×</button></p>)}<footer><button onClick={()=>setDraft(a=>[...a,{status_type:'bleed',potency:1,count:1}])}>+ Efeito</button><button onClick={()=>setOpen(false)}>Cancelar</button><button disabled={saving} onClick={save}>{saving?'Salvando…':'Salvar efeitos'}</button></footer>{error&&<p className="edit-error">{error}</p>}</div>}</section><section className="status-resistances"><header><ShieldCheck/><span>RESISTÊNCIAS</span></header>{character.resistances?.map(x=><div key={x.name}><span>{x.name}</span><b>{x.value||x.tier||'1.0×'}</b></div>)}</section></div>
}
